# SPDX-FileCopyrightText: 2022 - 2024 Robin Vobruba <hoijui.quaero@gmail.com>
# SPDX-FileCopyrightText: 2022 Andre Lehmann <aisberg@posteo.de>
#
# SPDX-License-Identifier: CC0-1.0

user_agent: "OKH-LOSH-Crawler github.com/iop-alliance/OpenKnowHow"  # (opt)

# for crawler state
database:
  type: file       # (opt) nothing else implemented
  path: ./workdir  # (opt)

repositories:
  file:
    workdir: ./workdir  # (opt)

fetchers:
  defaults:      # (opt) default values for fetchers
    retries: 3   # (opt) default number of retries
    timeout: 10  # (opt) default request timeout
  github.com:
    retries: 3   # (opt) fetcher specific number of retries
    timeout: 15  # (opt) fetcher specific request timeout
    access_token: xxxxxxxxxx  # (req) personal access token to use the GitHub API; generation instructions: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-personal-access-token-classic
  oshwa.org:
    retries: 3   # (opt) fetcher specific number of retries
    timeout: 15  # (opt) fetcher specific request timeout
    access_token: xxxxxxxxxx  # (req) personal access token to use the OSHWA API; get from here: https://certificationapi.oshwa.org/
  thingiverse.com:
    retries: 3   # (opt) fetcher specific number of retries
    timeout: 15  # (opt) fetcher specific request timeout
    access_token: xxxxxxxxxx  # (req) app access token to use the Thingiverse API
