#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2024 Robin Vobruba <hoijui.quaero@gmail.com>
# SPDX-License-Identifier: Unlicense
#
# See the output of "$0 -h" for details.

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
#set -Eeu

script_path="$(readlink -f "${BASH_SOURCE[0]}")"
script_dir="$(dirname "$script_path")"
script_name="$(basename "$script_path")"
project_dir="$(dirname "$script_dir")"
# workdir="$project_dir/workdir"
assets_dir="$project_dir/krawl/assets"
api_docu_dir="$assets_dir/api_docu"

# initial default values
APP_NAME="RDF Serialization check"
overwrite=false
all=false

print_help() {

	echo "$APP_NAME - Downloads all latest API specs,"
	echo "for:"
	echo
	echo "- OSHWA"
	echo "- Thingiverse"
	echo
	echo "Usage:"
	echo "  $script_name [OPTION...]"
	echo "Options:"
	echo "  -h, --help"
	echo "    Shows this help message and exit"
	echo "  -o, --overwrite"
	echo "    Overwrites existing files"
	echo "  -a, --all"
	echo "    Downloads all API specs (default: Only relevant ones)"
	echo "Examples:"
	echo "  $script_name"
	echo "  $script_name --help"
	echo "  $script_name --overwrite"
}

# Process command line arguments
while [[ $# -gt 0 ]]
do
	arg="$1"
	shift # $2 -> $1, $3 -> $2, ...

	case "$arg" in
		-h|--help)
			print_help
			exit 0
			;;
		-o|--overwrite)
			overwrite=true
			;;
		-a|--all)
			all=true
			;;
		*) # non-/unknown option
			>&2 echo "Unknown arg: '$arg'"
			exit 1
			;;
	esac
done

function log() {
    local level timestamp
    level="$(printf '%s' "$1" | tr '/a-z/' '/A-Z/')"
    # timestamp="$(date +'%Y-%m-%d %H:%M:%S')"
    timestamp="$(date --iso-8601=seconds)"
    shift
    >&2 echo "$timestamp $level $*"
}

function download() {
    local url file_path
    url="$1"
    file_path="$2"

    mkdir -p "$(dirname "$file_path")"
    if $overwrite || [ ! -e "$file_path" ]
    then
        log info "Downloading '$url' to '$file_path' ..."
        wget \
            --quiet \
            -O "$file_path" \
            "$url"
    else
        log info "Already present, skipping download of '$file_path'."
    fi
}

function prettify_json() {
    local json_file tmp_file
    json_file="$1"
    tmp_file="${json_file%.json}.tmp.json}"

    jq \
        < "$json_file" \
        > "$tmp_file"
    mv "$tmp_file" "$json_file"
}

function yaml2json() {
    local yaml_file json_file
    yaml_file="$1"
    json_file="${2:-${yaml_file%.yaml}.json}"

    yq r \
        --tojson \
        --prettyPrint \
        "$yaml_file" \
        > "$json_file" \
        || true
}

# OSHWA
oshwa_dir="$api_docu_dir/oshwa"
mkdir -p "$oshwa_dir"
download \
    "https://certificationapi.oshwa.org/open-api-spec" \
    "$oshwa_dir/open-api-spec.json"
prettify_json "$oshwa_dir/open-api-spec.json"

# Thingiverse
tv_dir="$api_docu_dir/thingiverse"
mkdir -p "$tv_dir"
tv_specs_url="https://www.thingiverse.com/swagger/docs"

function tv_dl() {
    local yaml_file_ref json_file
    yaml_file_ref="$1"
    url="$tv_specs_url/$yaml_file_ref"
    yaml_file="$tv_dir/$(basename "$yaml_file_ref")"
    json_file="${2:-${yaml_file%.yaml}.json}"

    download "$url" "$yaml_file"
    yaml2json "$yaml_file" "$json_file"
    # echo "$json_file"
}

tv_dl "openapi.yaml"
if $all
then
    grep \
        -r \
        '".ref"' "$tv_dir/openapi.json" \
        | sed \
            -E \
            -e 's|[ \t]*".ref": "||' \
            -e 's|"$||' \
            -e 's|#.*$||' \
        | sort -u \
        | while read -r ref
    do
        tv_dl "$ref"
    done
else
    for cat_name in category collection email file image_summary tag thing user
    do
        tv_dl "resources/${cat_name}.yaml"
        tv_dl "schemas/${cat_name}_schema.yaml"
    done
fi

# GitHub
gh_dir="$api_docu_dir/github"
mkdir -p "$gh_dir"
#gh_repo_url="https://github.com/github/rest-api-description"
gh_gql_schema="https://docs.github.com/public/fpt/schema.docs.graphql"
gh_rest_schema="https://github.com/github/rest-api-description/raw/refs/heads/main/descriptions/api.github.com/api.github.com.json"

download \
    "$gh_gql_schema" \
    "$gh_dir/$(basename "$gh_gql_schema")"
download \
    "$gh_rest_schema" \
    "$gh_dir/$(basename "$gh_rest_schema")"

echo "done."
